src/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers, permissions

from api.views import UserViewSet, QuestionDetailView, QuizListView

router = routers.DefaultRouter()
router.register(r"custom-users", UserViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    # path("", include(router.urls)),
    # path("auth/", include('rest_framework.urls')),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("auth/", include("djoser.urls")),
    path("auth/jwt/", include("djoser.urls.jwt")),
    path(
        "quiz/<uuid:uuid>/questions/<int:order_number>/",
        QuestionDetailView.as_view(),
        name="question_detail",
    ),
    path("quiz/", QuizListView.as_view(), name="quiz_list"),
]

src/quiz/urls.py
from django.urls import path

from quiz.views import Index, QuizDetails, QuestionView, ResultDetails

app_name = "quiz"


urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("quiz/<uuid:uuid>", QuizDetails.as_view(), name="quiz_details"),
    path(
        "quiz/<uuid:uuid>/questions/<int:order>",
        QuestionView.as_view(),
        name="quiz_question",
    ),
    path("quiz/result/<uuid:uuid>", ResultDetails.as_view(), name="result_details"),
]

src/quiz/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth import get_user_model

from quiz.services.utils import generate_uuid


class BaseModel(models.Model):
    class Meta:
        abstract = True

    create_date = models.DateTimeField(null=True, auto_now_add=True)
    last_update = models.DateTimeField(null=True, auto_now=True)


class Quiz(BaseModel):
    class LEVEL_CHOICES(models.IntegerChoices):  # noqa:
        BASIC = 0, "Junior"
        MIDDLE = 1, "Middle"
        SENIOR = 2, "Senior"

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    level = models.PositiveSmallIntegerField(
        choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE
    )
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=1024, null=True, blank=True)  # noqa
    image = models.ImageField(default="default.png", upload_to="covers")

    def __str__(self):
        return f"{self.title}"

    def questions_count(self):
        return self.questions.count()


class Question(BaseModel):
    quiz = models.ForeignKey(
        to=Quiz, related_name="questions", on_delete=models.CASCADE
    )
    order_number = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(settings.QUESTION_MAX_LIMIT)]
    )
    text = models.CharField(max_length=256)

    def __str__(self):
        return f"{self.text}"


class Choice(BaseModel):
    question = models.ForeignKey(
        to=Question, related_name="choices", on_delete=models.CASCADE
    )
    is_correct = models.BooleanField(default=False)
    text = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.text}"


class Result(BaseModel):
    class STATE(models.IntegerChoices):  # noqa:
        NEW = 0, "New"
        IN_PROGRESS = 1, "In progress"
        FINISHED = 2, "Finished"

    quiz = models.ForeignKey(to=Quiz, related_name="results", on_delete=models.CASCADE)
    user = models.ForeignKey(
        to=get_user_model(), related_name="results", on_delete=models.CASCADE
    )
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    num_of_corrects_answers = models.PositiveSmallIntegerField(
        default=0, validators=[MaxValueValidator(settings.QUESTION_MAX_LIMIT)]
    )

src/quiz/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import DetailView, ListView

from quiz.models import Quiz, Question, Result

from quiz.tasks import mine_bitcoin, normalize_email_task


class Index(ListView):
    template_name = "index.html"
    queryset = Quiz.objects.all()
    context_object_name = "all_quiz"
    paginate_by = 1


class QuizDetails(DetailView):
    template_name = "quiz_details.html"
    model = Quiz

    def get_object(self, queryset=None):
        return Quiz.objects.get(uuid=self.kwargs.get("uuid"))


class ResultDetails(DetailView):
    template_name = "quiz_results.html"
    model = Result

    def get_object(self, queryset=None):
        return Result.objects.get(uuid=self.kwargs.get("uuid"))


class QuestionView(DetailView):
    # TemplateView
    template_name = "questions.html"
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["quiz"] = Quiz.objects.get(uuid=self.kwargs.get("uuid"))
        return context

    def get_object(self, queryset=None):
        return Question.objects.get(
            quiz__uuid=self.kwargs.get("uuid"), order_number=self.kwargs.get("order")
        )

    def check_correct_answer(self, question_instance, result_instance) -> None:
        right_answer = question_instance.choices.filter(is_correct=True).first()
        answer = int(self.request.POST.get("checkbox"))

        if right_answer.id == answer:
            result_instance.num_of_corrects_answers += 1
            result_instance.save()

    def post(self, request, uuid, order, **kwargs):
        question_instance = Question.objects.get(
            quiz__uuid=self.kwargs.get("uuid"), order_number=self.kwargs.get("order")
        )
        current_quiz = Quiz.objects.get(uuid=uuid)
        if order == 1:
            result_instance = Result.objects.create(
                quiz=current_quiz, user=self.request.user
            )
            self.request.session["result_instance"] = str(result_instance.uuid)
            self.check_correct_answer(question_instance, result_instance)

        elif order == current_quiz.questions.count():
            result_instance = Result.objects.get(
                uuid=self.request.session.get("result_instance")
            )
            self.check_correct_answer(question_instance, result_instance)
            return HttpResponseRedirect(
                reverse("quiz:result_details", kwargs={"uuid": result_instance.uuid})
            )
        else:
            result_instance = Result.objects.get(
                uuid=self.request.session.get("result_instance")
            )
            self.check_correct_answer(question_instance, result_instance)

        next_page = order + 1
        return HttpResponseRedirect(
            reverse("quiz:quiz_question", kwargs={"uuid": uuid, "order": next_page})
        )


def bitcoin(request):
    mine_bitcoin.delay()

    return HttpResponse("Will finish in.")


def normalize_email(request):
    normalize_email_task.delay(filter=dict(email__endswith=".com"))
    return HttpResponse("Done")

src/quiz/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Xtra Blog</title>
	<link rel="stylesheet" href="fontawesome/css/all.min.css"> <!-- https://fontawesome.com/ -->
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/templatemo-xtra-blog.css" rel="stylesheet">
<!--
    
TemplateMo 553 Xtra Blog

https://templatemo.com/tm-553-xtra-blog

-->
</head>
<body>
	<header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
                <h1 class="text-center">Xtra Blog</h1>
            </div>
            <nav class="tm-nav" id="tm-nav">            
                <ul>
                    <li class="tm-nav-item"><a href="index.html" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog Home
                    </a></li>
                    <li class="tm-nav-item"><a href="quiz_details.html" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Single Post
                    </a></li>
                    <li class="tm-nav-item active"><a href="about.html" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Xtra
                    </a></li>
                    <li class="tm-nav-item"><a href="contact.html" class="tm-nav-link">
                        <i class="far fa-comments"></i>
                        Contact Us
                    </a></li>
                </ul>
            </nav>
            <div class="tm-mb-65">
                <a href="https://facebook.com" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            <p class="tm-mb-80 pr-5 text-white">
                Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>
        </div>
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
                        <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>                                
                    </form>
                </div>                
            </div>            
            <div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                    <img src="img/about-01.jpg" alt="Image" class="img-fluid">
                </div>
            </div>
            <div class="row tm-row tm-mb-40">
                <div class="col-12">                    
                    <div class="mb-4">
                        <h2 class="pt-2 tm-mb-40 tm-color-primary tm-post-title">About this xtra blog</h2>
                        <p>
                            You can immediately download 
                                <a rel="nofollow" href="https://templatemo.com/tm-553-xtra-blog" target="_blank">Xtra Blog Template</a> 
                                from TemplateMo website for 100% free of charge. Etiam vehicula, tortor ac eleifend tincidunt, diam neque pellentesque ipsum, 
                                a geugiat eros mauris eget lorem. Quisque in
                            bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. Aliquam lorem mi, maximus at iaculis ut, viverra vel
                            mauris. Duis congue luctus metus, sodales tincidunt lectus fringilla ut. Nunc tempus at magna sed vestibulum.
                        </p>
                        <p>
                            Proin et arcu ligula. Praesent quis erat eu est solliditudin tristique ut in arcu. Donec bibendum ex id ligula semper dictum.
                            Proin malesuada luctus auctor. Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in
                            malesuada nulla magna ut enim. Morbi lacinia magna sed sapien auctor, vitae luctus nunc cursus.
                        </p>                            
                    </div>                    
                </div>
            </div>
            <div class="row tm-row tm-mb-120">
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-bezier-curve fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Background</h2>
                        <p class="mb-0 tm-line-height-short">
                            Phasellus pulvinar nisl ornare leo porttitor, et vestibulum lorem semper. 
                            Duis risus ex, molestie sit amet magna in,
                            pharetra pellentesque est. Curabitur elit metus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fas fa-users-cog fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Teamwork</h2>
                        <p class="mb-0 tm-line-height-short">
                            Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in malesuada nulla magna ut enim. 
                            Morbi lacinia magna sed auctor, vitae nunc cursus.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 tm-about-col">
                    <div class="tm-bg-gray tm-about-pad">
                        <div class="text-center tm-mt-40 tm-mb-60">
                            <i class="fab fa-creative-commons-sampling fa-4x tm-color-primary"></i>                            
                        </div>                        
                        <h2 class="mb-3 tm-color-primary tm-post-title">Our Core Value</h2>
                        <p class="mb-0 tm-line-height-short">
                            Nunc mi ante, suscipit vel dapibus et, volutpat sit amet ante. In tempor nec sem vitae varius. Aliquam tincidunt orci sem, et imperdiet massa consectetur nec.
                        </p>
                    </div>
                </div>
            </div>            
            <div class="row tm-row tm-mb-60">
                <div class="col-12">
                    <hr class="tm-hr-primary  tm-mb-55">
                </div>                
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-02.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">John Henry</h2>
                            <h3 class="tm-h3 mb-3">CEO/Founder</h3>
                            <p class="mb-0 tm-line-height-short">
                                Aliquam non vulputate lectus, vel ultricies diam. Suspendisse at ipsum
                                hendrerit, vestibulum mi id, mattis tortor.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-03.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Timy Cake</h2>
                            <h3 class="tm-h3 mb-3">Project Director</h3>
                            <p class="mb-0 tm-line-height-short">
                                Quisque in bibendum elit, in egestas turpis. Vestibulum ornare sollicitudin congue. 
                                Aliquam lorem mi, maximus at iaculis ut.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-04.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Jay Zoona</h2>
                            <h3 class="tm-h3 mb-3">Supervisor</h3>
                            <p class="mb-0 tm-line-height-short">
                                Maecenas eu mi eu dui cursus consequat non eu metus. Morbi ac
                                turpis eleifend, commodo purus eget, commodo mauris.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 tm-mb-60 tm-person-col">
                    <div class="media tm-person">
                        <img src="img/about-05.jpg" alt="Image" class="img-fluid mr-4">
                        <div class="media-body">
                            <h2 class="tm-color-primary tm-post-title mb-2">Catherine Soft</h2>
                            <h3 class="tm-h3 mb-3">Team Leader</h3>
                            <p class="mb-0 tm-line-height-short">
                                Integer eu sapien hendrerit,
                                imperdiet arcu sit amet, sollicitudin ipsum.
                                Phasellus consequat suscipit ligula eget bibendum.
                            </p>
                        </div>
                    </div>
                </div>
            </div>        
            <footer class="row tm-row">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright 2020 Xtra Blog Company Co. Ltd.
                </div>
            </footer>
        </main>
    </div>
    <script src="js/jquery.min.js"></script>
    <script src="js/templatemo-script.js"></script>
</body>
</html>

src/quiz/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My test Blog</title>
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap"
          rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="{% static 'css/bootstrap.min.css' %}" type="text/css"
          rel="stylesheet">
    <link href="{% static 'css/templatemo-xtra-blog.css' %}" type="text/css"
          rel="stylesheet">
    <!--

    TemplateMo 553 Xtra Blog

    https://templatemo.com/tm-553-xtra-blog

    -->
</head>
<body>
<header class="tm-header" id="tm-header">
    <div class="tm-header-wrapper">
        <button class="navbar-toggler" type="button"
                aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="tm-site-header">
            <div class="mb-3 mx-auto tm-site-logo"><i
                    class="fas fa-times fa-2x"></i></div>
            <h1 class="text-center">Xtra Blog</h1>
        </div>
        <nav class="tm-nav" id="tm-nav">
            <ul>
                <li class="tm-nav-item active"><a href="{% url 'quiz:index' %}"
                                                  class="tm-nav-link">
                    <i class="fas fa-home"></i>
                    Blog Home
                </a></li>
                <li class="tm-nav-item"><a href="quiz_details.html"
                                           class="tm-nav-link">
                    <i class="fas fa-pen"></i>
                    Single Post
                </a></li>
                <li class="tm-nav-item"><a href="about.html"
                                           class="tm-nav-link">
                    <i class="fas fa-users"></i>
                    About Xtra
                </a></li>
                <li class="tm-nav-item"><a href="contact.html"
                                           class="tm-nav-link">
                    <i class="far fa-comments"></i>
                    Contact Us
                </a></li>
            </ul>
        </nav>
        <div class="tm-mb-65">
            <a rel="nofollow" href="https://fb.com/templatemo"
               class="tm-social-link">
                <i class="fab fa-facebook tm-social-icon"></i>
            </a>
            <a href="https://twitter.com" class="tm-social-link">
                <i class="fab fa-twitter tm-social-icon"></i>
            </a>
            <a href="https://instagram.com" class="tm-social-link">
                <i class="fab fa-instagram tm-social-icon"></i>
            </a>
            <a href="https://linkedin.com" class="tm-social-link">
                <i class="fab fa-linkedin tm-social-icon"></i>
            </a>
        </div>
        <p class="tm-mb-80 pr-5 text-white">
            Xtra Blog is a multi-purpose HTML template from TemplateMo website.
            Left side is a sticky menu bar. Right side content will scroll up
            and down.
        </p>
    </div>
</header>
<div class="container-fluid">
    <main class="tm-main">
        <!-- Search form -->
        <div class="row tm-row">
            <div class="col-12">
                <form method="GET" class="form-inline tm-mb-80 tm-search-form">
                    <input class="form-control tm-search-input" name="query"
                           type="text" placeholder="Search..."
                           aria-label="Search">
                    <button class="tm-search-button" type="submit">
                        <i class="fas fa-search tm-search-icon"
                           aria-hidden="true"></i>
                    </button>
                </form>
            </div>
        </div>
        {% block content %}
            <div class="row tm-row">
                {% for quiz in all_quiz %}
                    <article class="col-12 col-md-6 tm-post">
                        <hr class="tm-hr-primary">
                        <a href="{% url 'quiz:quiz_details' uuid=quiz.uuid %}"
                           class="effect-lily tm-post-link tm-pt-60">
                            <div class="tm-post-link-inner">
                                <img src="{{ quiz.image.url }}" alt="Image"
                                     class="img-fluid">
                            </div>
                            <span class="position-absolute tm-new-badge">{{ quiz.get_level_display }}</span>
                            <h2 class="tm-pt-30 tm-color-primary tm-post-title">
                                {{ quiz.title }}</h2>
                        </a>
                        <p class="tm-pt-30">
                            {{ quiz.description }}
                        </p>
                        <div class="d-flex justify-content-between tm-pt-45">
                            <span class="tm-color-primary">Created</span>
                            <span class="tm-color-primary">{{ quiz.create_date }}</span>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between">
                            <span>{{ quiz.questions_count }} questions</span>
                            <span>to be add</span>
                        </div>
                    </article>
                {% endfor %}
            </div>
            {% if page_obj.paginator.num_pages > 1 %}
                <div class="row tm-row tm-mt-100 tm-mb-75">
                    <div class="tm-prev-next-wrapper">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}"
                               class="mb-2 tm-btn tm-btn-primary tm-prev-next">Prev</a>
                        {% else %}
                            <a class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled"
                               disabled>Prev</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}"
                               class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
                        {% else %}
                            <a class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled"
                               disabled>Next</a>
                        {% endif %}

                    </div>
                    <div class="tm-paging-wrapper">
                        <span class="d-inline-block mr-3">Page</span>
                        <nav class="tm-paging-nav d-inline-block">
                            <ul>
                                {% for page_number in page_obj.paginator.page_range %}
                                    {% if page_number == page_obj.number %}
                                        <li class="tm-paging-item active">
                                            <a href="?page={{ page_number }}"
                                               class="mb-2 tm-btn tm-paging-link">{{ page_number }}</a>
                                        </li>
                                    {% else %}
                                        <li class="tm-paging-item">
                                            <a href="?page={{ page_number }}"
                                               class="mb-2 tm-btn tm-paging-link">{{ page_number }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        {% endblock %}
        <footer class="row tm-row">
            <hr class="col-12">
            <div class="col-md-6 col-12 tm-color-gray">
                Design: <a rel="nofollow" target="_parent"
                           href="https://templatemo.com"
                           class="tm-external-link">TemplateMo</a>
            </div>
            <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                Copyright 2020 Xtra Blog Company Co. Ltd.
            </div>
        </footer>
    </main>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
    function checkboxReset(checkbox) {
        let checkboxes = document.getElementsByName('checkbox')
        checkboxes.forEach((item) => {
                if (item !== checkbox) item.checked = false
            }
        )
    }
</script>
<script src="{% static 'js/templatemo-script.js' %}"></script>
</body>
</html>

src/quiz/templates/questions.html
{% extends 'index.html' %}

{% block content %}
    <div class="row tm-row">
        <div class="col-12">
            <hr class="tm-hr-primary tm-mb-55">

            <div class="container mt-5">
                <div class="d-flex justify-content-center row">
                    <div class="col-md-10 col-lg-10">
                        <div class="border">
                            <form method="post">
                                {% csrf_token %}
                                <div class="question bg-white p-3 border-bottom">
                                    <div class="d-flex flex-row justify-content-between align-items-center mcq">
                                        <h4>{{ quiz.title }}</h4>
                                        <span>Count of questions: {{ quiz.questions_count }}</span>
                                    </div>
                                </div>
                                <div class="question bg-white p-3 border-bottom">
                                    <div class="d-flex flex-row align-items-center question-title">
                                        <h3 class="text-danger">Q.</h3>
                                        <h5 class="mt-1 ml-2">{{ question.text }}</h5>
                                    </div>
                                    {% for choice in question.choices.all %}
                                        <div class="ans ml-2">
                                            <label class="checkbox"> <input
                                                    onclick="checkboxReset(this)"
                                                    type="checkbox"
                                                    name="checkbox"
                                                    value="{{ choice.id }}">
                                                <span>{{ choice.text }}</span>
                                            </label>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="d-flex flex-row justify-content-between align-items-center p-3 bg-white">
                                    <button class="btn-primary border-success align-items-center btn-success"
                                            type="submit">Next <i
                                            class="fa fa-angle-right ml-2"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}